title: <p align="center"> Tirthankar Paul </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  
  <a href="https://www.linkedin.com/in/tirthankar-paul/">LinkedIn</a> |
  <a href="https://github.com/TirthankarPaul">GitHub</a>
  
  <br>   
  Researcher and Data Analyst. I'm working on Data Science, Big Data, Machine learning & NLP related problems.
  <br>
  </p>

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
