title: <p align="center"> Tirthankar Paul </p>
logo: /assets/img/logo.png
description:
  <p align="left">
  
  <a href="https://www.linkedin.com/in/tirthankar-paul/">LinkedIn</a> |
  <a href="https://github.com/TirthankarPaul">GitHub</a> |
  <a href="https://orcid.org/0000-0002-1115-0843">ORCiD</a> |
  <a href="https://scholar.google.com/citations?user=c5j1DXgAAAAJ&hl=en">Google Scholar</a>
  
  <br>   
  Researcher and Data Analyst in Data Science on Big Data, Machine learning, Deep Learning & NLP related problems.
  <br>
  
  
  
  
  
  </p>

theme: jekyll-theme-minimal
